application: youforrexapp
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: web.pages.home.app

- url: .*
  script: web.pages.home.app


libraries:
- name: webapp2
  version: "2.5.2"
